name: samo_agents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fenics=2019.1.0
  - mshr=2019.1.0
  - setuptools<70
  - h5py
  - nlopt
  - gemseo
  - fenics-adjoint
  - pip
  - pytest
  - pytest-cov
  - coverage
  - sphinx
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinxcontrib-mermaid
  - nbsphinx
  - jupyterlab
  - jupytext
  - pandoc
  - pip:
    - google-genai
    - typer
    - requests
