name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4

    - name: Cache Conda
      uses: actions/cache@v3
      env:
        CACHE_NUMBER: 1
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: samo_agents
        environment-file: environment.yml
        auto-activate-base: false
        miniforge-version: latest
        use-mamba: true

    - name: Run Pytest with Coverage
      env:
        PYTHONPATH: .
      run: |
        pip install "setuptools<70"
        pytest --cov=ggp --cov-report=json tests/
        PERCENT=$(jq '.totals.percent_covered' coverage.json)
        COLOR=$(python3 -c "print('green' if $PERCENT > 80 else 'yellow' if $PERCENT > 50 else 'red')")
        mkdir -p badges
        echo "{\"schemaVersion\": 1, \"label\": \"coverage\", \"message\": \"${PERCENT%.*}%\", \"color\": \"$COLOR\"}" > badges/coverage.json

    - name: Deploy Coverage JSON
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: badges
        publish_branch: gh-pages
        destination_dir: badges
        keep_files: true
